[project]
name = "assignment"
version = "0.1.0"
description = "Repo for NLP 2025 final assignment."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "ddgs>=9.6.1",
    "openai>=2.6.1",
    "requests>=2.32.5",
]
